name: NeoChars
author: Neoblade298
main: me.Neoblade298.NeoChars.Main
version: 1.1
api-version: 1.15
depend: [SkillAPI, MCCore]
commands:
  char:
    description: Views a player's character
    usage: /char [player]